// 120+ Real Gold Coast Commercial Corridors, Boulevards, and Residential Streets
export const goldCoastStreets: string[] = [
  'Admiralty Drive',
  'Albert Avenue',
  'Albatross Avenue',
  'Allambie Lane',
  'Armrick Avenue',
  'Ashmore Cut',
  'Ashmore Road',
  'Australia Avenue',
  'Bauer Street',
  'Bayview Street',
  'Benowa Road',
  'Bermuda Street',
  'Boobegan Road',
  'Brisbane Road',
  'Broadbeach Boulevard',
  'Bundall Road',
  'Burleigh Connection Road',
  'Captain Cook Drive',
  'Carrara Street',
  'Cavill Avenue',
  'Charles Avenue',
  'Cheltenham Drive',
  'Christine Avenue',
  'Clifford Street',
  'Commodore Drive',
  'Como Crescent',
  'Coolangatta Road',
  'Coomera Parkway',
  'Cotlew Street',
  'Craft Court',
  'Cronin Island',
  'Cypress Avenue',
  'Davenport Street',
  'Days Road',
  'Discovery Drive',
  'Dunlop Court',
  'Duringan Street',
  'Edinburgh Drive',
  'Elanora Drive',
  'Elkhorn Avenue',
  'Eugaree Street',
  'Ferny Avenue',
  'Ferry Road',
  'Foxwell Road',
  'Garfield Terrace',
  'Gilston Road',
  'Gold Coast Highway',
  'Gold Coast Springbrook Road',
  'Griffith Street',
  'Guineas Creek Road',
  'Hamilton Avenue',
  'Hanlan Street',
  'Hardys Road',
  'Hedges Avenue',
  'Heeb Street',
  'Helensvale Road',
  'High Street',
  'Hollywell Road',
  'Hooker Boulevard',
  'Hope Island Road',
  'Isle of Capri Via Roma',
  'Johnston Street',
  'Jubilee Avenue',
  'Kumbari Avenue',
  'Labrador Boulevard',
  'Lake Orr Drive',
  'Lawson Street',
  'Marine Parade',
  'Markeri Street',
  'Miles Street',
  'Monaco Street',
  'Morala Avenue',
  'Mudgeeraba Road',
  'Musgrave Hill Road',
  'Musgrave Street',
  'Napper Road',
  'Nerang Street',
  'Nerang-Broadbeach Road',
  'Nineteenth Avenue',
  'Northcliffe Drive',
  'Ocean Avenue',
  'Olsen Avenue',
  'Oxenford-Tamborine Road',
  'Oxley Drive',
  'Palm Beach Avenue',
  'Pappas Way',
  'Paradise Point Esplanade',
  'Queen Street',
  'Queensland Avenue',
  'Railway Street',
  'Reedy Creek Road',
  'Remembrance Drive',
  'Reserve Road',
  'Rio Vista Boulevard',
  'Robina Parkway',
  'Runaway Bay Drive',
  'Santa Barbara Road',
  'Santa Monica Road',
  'Scarborough Street',
  'Scottsdale Drive',
  'Short Street',
  'Sickle Avenue',
  'Siganto Drive',
  'Southport-Nerang Road',
  'Staghorn Avenue',
  'Strathaird Road',
  'Sunset Boulevard',
  'Sunshine Boulevard',
  'Surf Parade',
  'Surfers Central',
  'Surfers Paradise Boulevard',
  'Tamborine Oxenford Road',
  'Tedder Avenue',
  'Teemangum Street',
  'The Esplanade (Burleigh Heads)',
  'The Esplanade (Surfers Paradise)',
  'Trees Road',
  'University Drive',
  'Upton Street',
  'Varsity Parade',
  'Victoria Avenue',
  'View Avenue',
  'Wardoo Street',
  'Waterfront Boulevard',
  'Wharf Road',
  'Worongary Road'
];
